### ISSUE TITLE
Maximum and Minimum are omitted if set to zero

### ISSUE THREAD

**Issue by alexis-miakouikila** [nytimes/openapi2proto#124]
Given a definition of the type:

```yaml
FinanceConfiguration:
      commission:
        type: number
        format: double
        maximum: 100
        minimum: 0
```

The value of minimum is lost because it has been set to zero.

I believe the issue comes from: https://github.com/nytimes/openapi2proto/blob/master/openapi/interface.go#L161
where maximum and minimum are omitted if "empty".
