### ISSUE TITLE
Support ability to add field options to generated protobuf

### ISSUE THREAD

**Issue by joshua-bell-sonrai** [nytimes/openapi2proto#134]
### Reason
It would be nice if the ability to add custom field options. 

### Example

**input**
```
Config:
    type: object
    required:
      - config
    properties:
      config:
        type: string
        fieldOption: [ (graphqlOverride) = { type: "DateTime" } ]
```

**output**
```
message Config {
    string config = 1 [ (graphqlOverride) = { type: "DateTime" } ];
}
```
