### ISSUE TITLE
integer, long number type should be written as int32, int64

### ISSUE THREAD

**Issue by drmaas** [NYTimes/openapi2proto#62]
```
    properties:
      value:
        type: number
        format: long
        description: Numerical duration length.
        default: 8
```

long is a valid swagger type. This should be written as `int64` in protobuf format. Currently it is written as `long`.

Same issue occurs for `integer` - it should be written as `int32`.
