### ISSUE TITLE
Allow untyped objects to be specified as bytes

### ISSUE THREAD

**Issue by drmaas** [NYTimes/openapi2proto#99]
In many of our specs, we have things like this:

```
      authorization_data:
        type: object
        description: Data, as an arbitrary json blob
``` 
or
```
      authorization_data:
        type: object
        description: Data, as an arbitrary json blob
        additionalProperties: true
```

This allows arbitrary data, per https://swagger.io/docs/specification/data-models/dictionaries/

Currently, this will be generated as an empty `Message` or a `map<string, empty Message>` by this library. This does't work well. My proposal is that these should actually be modeled as the scalar type `bytes`. That way, whatever language implementation is using the schema can decide how to convert the arbitrary data into and from bytes.

Another option would be to use `google.protobuf.Any`, as it does basically the same thing, but also allows packing/unpacking to different `Message` types.

@jprobinson any thoughts on what is preferred?
